### PR TITLE
compatability with latest web3.py

### PR DESCRIPTION
**Pull request by darkerego**
In the latest version of web3.py, the `geth_poa_middleware` library has been renamed  `ExtraDataToPOAMiddleware`. As a quick fix, I simply changed the import statement to `from web3.middleware import ExtraDataToPOAMiddleware as geth_poa_middleware`

### CODE REVIEW

**Comment by RichardAtCT** [comment]
Thanks for this! Can you please also update setup.py and requirements.txt with the correct web3.py library otherwise this would break for people using an Oliver version of web3.py

**Comment by darkerego** [comment]
Yes will do today

**Review by darkerego — COMMENTED** [review]
Okay, I have update the requirements, the setup script and tested to make sure that works. Furthermore I cleaned this up a bit. I added some functionality to dynamically determine whether we are on a POA chain and if so inject the middleware. Let me know if you need anything else.

**Review by RichardAtCT — APPROVED** [review]
Looks good!

**Comment by RichardAtCT** [comment]
Thanks for the work @darkerego <3

**Comment by darkerego** [comment]
> Thanks for the work @darkerego <3

My pleasure. I have working code for multicall, I saw you had a note in there to implement that at some point, I can look at that and implement it if you want?

**Comment by RichardAtCT** [comment]
> > Thanks for the work @darkerego <3
> 
> My pleasure. I have working code for multicall, I saw you had a note in there to implement that at some point, I can look at that and implement it if you want?

That would be great - thanks!

**Pull request merged**
